name: rex
description: A multi-business app

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  mj_image_slider: ^0.0.7
  font_awesome_flutter: ^10.1.0
  persistent_bottom_nav_bar: ^5.0.2
  auto_route: ^5.0.4
  provider: ^6.0.5
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  get: ^4.6.5
  cloud_firestore: ^4.5.2
  flutter_svg: ^1.1.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mailer: ^6.0.1
  google_sign_in: ^6.1.4
  emailjs: ^1.1.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - images/
     - images/cartimages/
     - videos/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
